### ISSUE TITLE
"I'm afraid I can't do that" response

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/matrix-service#19]
Depending on normalization, batch correction, etc, there are matrices that the matrix service could mechanistically create that would mislead data consumers. For example, an expression matrix generated from HCA data could contain obvious batch effects, but a user may not know that or how to address it.

We need to figure out how (and if) to prevent such a situation. There are a few ways we could do it, from just returning a 4xx based on some policy, to sometimes delivering multiple matrices, to running some future standard batch correction method.

This is a broad concern and requires guidance from HCA scientific leadership. This issue is mostly to flag the problem and solicit that guidance.

**Comment by TimothyTickle** [comment]
At a first glance:
- I think the matrices I would be timid to deliver would be ones that combine assays (like SS2 and 10X measurements in the same matrix) and multispecies matrices (if we have multiple species in the DCP).
- Although I don't think we will have this in the DCP, I would not combine outputs from different pipeline versions that are scientifically different (or are derived from different reference versions).
- We would need to clearly error with no delivery so the scientists know they did not have something delivered, anything outside of an error has the potential for being used.
- If normalization is performed, it would need to be performed on all cells in the matrix.
- If batch effect correction is performed, it would need to be performed using all cells in the matrix as input unless the methodology indicated otherwise.
- Once filtering or batch effect correction is included the order of operations becomes important.

I added this to the next AWG pipelines subworking group meeting agenda.

**Comment by brianraymor** [comment]
@TimothyTickle - when is the next AWG pipelines subworking group meeting?
