### ISSUE TITLE
3rd party libraries in use are tracked and analyzed for security risk

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/matrix-service#215]
DevSecOps team needs to tell us what tools to use to do this.
Then we will update all the component team tickets with that information.

**Comment by rhiananthony** [comment]
This has been completed for the repos owned by secondary analysis

**Comment by brianraymor** [comment]
@rhiananthony - I don't understand your reference _to done for ...secondary analysis_ above (or why it's in a matrix service issue). This issue is part of an epic that was blocked by - https://github.com/humancellatlas/dcp/issues/308 - basically a clarification from the DevSecOps team.

The expectation as outlined by @sampierson was that DevSecOps would update the dependent issues: _DevSecOps team needs to decide which tools to use. Then we will update all component tickets with this information._ This seems to have fallen on the floor.

**Comment by stahiri** [comment]
Per #308, DevSecOps recommendation is for everyone to use the same tool. Both Snyk and SourceClear are good options here. Prior recommendation from the team is to start with Snyk since it's open source (SourceClear requires procurement).

**Comment by stahiri** [comment]
@calvinnhieu - are you the best person to own this ticket/update as appropriate?

**Comment by stahiri** [comment]
Snyk has been implemented across the humancellatlas GitHub org
