### ISSUE TITLE
Investigate metadata schema changes

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#225]
Based on Parth's recommendation on [#matrix-dev](https://humancellatlas.slack.com/archives/CDSTJUP7Z/p1552591885001200), I've requested that @mckinsel and myself be added as future _FYI reviewers_ for metadata schema changes such as [New property migrations json file](https://github.com/HumanCellAtlas/metadata-schema/pull/833).

- [x] Review the recent [property_migrations.json](https://github.com/HumanCellAtlas/metadataschema/blob/integration/json_schema/property_migrations.json)
- [x] Review [style guide updates](https://github.com/HumanCellAtlas/metadata-schema/issues/691). There is a proposal to address all these in the April 2 Sprint. Checked items are already in Integration.
- [x] Capture [here] the required set of changes to the matrix service.

Parth already noted:

* _This includes the change to library_construction_method which breaks our ETL pipelines_
* _total_estimated_cells => estimated_cell_count feels like it will impact us as well_

**Comment by brianraymor** [comment]
- **library_preparation_protocol.json**

   _change **library_construction_approach** to **library_construction_method** to be consistent with all other protocol schemas using the term "method"_

https://github.com/HumanCellAtlas/matrix-service/blob/aa9558fae1417df93c79007a252c487fb8c45b62/matrix/common/etl/transformers/specimen_library.py#L250

        construction_approach = library_dict.get(
            "library_construction_approach", {}).get("ontology", "").upper()

**Comment by brianraymor** [comment]
There is an issue in their icebox - [Rename entity specimen_from_organism to body_part ](https://github.com/humancellatlas/metadata-schema/issues/389) that would impact cell_expression.py and specimen_library.py.

**Comment by brianraymor** [comment]
I've asked Mallory if process_type in analysis_process.json should be changed to be symmetrical with **process.json** - _change process_type to type to remove redundancy ("process")_. If true, this would impact:

https://github.com/HumanCellAtlas/matrix-service/blob/79a3cf1bc9322647846d94e3d7523941eff1009c/scripts/redshift/load_redshift.py#L38

**Comment by malloryfreeberg** [comment]
To help with tracking:

- **analysis_process.json**
  _change process_type to type to remove redundancy ("process")_
https://github.com/HumanCellAtlas/metadata-schema/issues/931

- **cell_suspension.json**
   _change **selected_cell_type** to  **selected_cell_types** because the field is an array_
https://github.com/HumanCellAtlas/metadata-schema/issues/923

- **contact.json**
   _change **contact_name** to **name** to remove redundant word (contact)_
https://github.com/HumanCellAtlas/metadata-schema/issues/927

- **publication.json**
  _change **publication_title** to **title** to remove redundancy_
https://github.com/HumanCellAtlas/metadata-schema/issues/928

**Comment by brianraymor** [comment]
Refined into separate issues tracking each set of .json changes.
