### ISSUE TITLE
There are some formatting issues with metadata causing annoyance for end users.

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/matrix-service#229]
Review and respond with a position to [Insight 4](https://docs.google.com/document/d/1qg4aPddgy2SFFKAxvwfZJTM4xDNVN4OgFuf5dAGD3bU/edit#heading=h.e2avnb2338u7)

_In the Loom file, the gene names in the first column are actually the transcript name, so they are not unique.  This leads to lots of repeats, and again, this first column can’t be used as a unique identifier.  2 participants mentioned this._

_The orientation of the expression matrix itself is opposite to what most users are familiar with (genes appear as rows, instead of cells as rows and genes as columns)._

**Comment by calvinnhieu** [comment]
_In the Loom file, the gene names in the first column are actually the transcript name, so they are not unique. This leads to lots of repeats, and again, this first column can’t be used as a unique identifier. 2 participants mentioned this._

This issue is addressed and a solution is explained in this [unreleased vignette](https://github.com/HumanCellAtlas/matrix-service/blob/mk-test-update/docs/Scanpy%20Loom%20Pancreas%20Notebook.ipynb):
"Scanpy reads the loom file correctly, but note that by default, scanpy uses the "Gene" field for variable names. It correctly complains that those are not unique. We can fix that by using scanpy's method, or we can specify the "Accession" field for variable names."
`adata = scanpy.read_loom("Single_cell_transcriptome_analysis_of_human_pancreas.loom", var_names="Accession")`

Next steps are to make this vignette publicly available.

_The orientation of the expression matrix itself is opposite to what most users are familiar with (genes appear as rows, instead of cells as rows and genes as columns)._

It is my understanding that the both orientations may be expected and choosing one would be arbitrary.

**Comment by brianraymor** [comment]
_We can fix that by using scanpy's method, or we can specify the "Accession" field for variable names._

What is _scanpy's method_?

_It is my understanding that the both orientations may be expected and choosing one would be arbitrary._

We can either document the orientation in the README -or- could add an option to the REST API to indicate orientation.

**Comment by brianraymor** [comment]
@mckinsel to document the orientation in the pending README.
