### ISSUE TITLE
Increase number of fq_ids that can be sent over POST

### ISSUE THREAD

**Issue by pcm32** [HumanCellAtlas/matrix-service#301]
I tried the service against one of the "small" HCA studies, trying to put all bundle_fqids in the json object to be posted, however I got back a message saying

```
b'{\n  "message": "List of bundle fqids is too large. Consider using bundle_fqids_url instead. Visit https://matrix.dev.data.humancellatlas.org for more information."\n}\n'
```
unfortunately we find the option of using a public URL to host a file with fqids slightly inconvenient. Is it possible to increase the limit of fqids that can be posted on the request to a realistic number for the available HCA studies? 

Thanks!

**Comment by brianraymor** [comment]
@pcm32 - The v0 API for the matrix service is primarily a contract between the data browser and the matrix service.

I'd encourage you to review the new [V1 API](https://matrix.dev.data.humancellatlas.org/) which is more developer-focused. 

Currently, *Swagger UI supports example but currently does not support [**multiple examples**](https://github.com/swagger-api/swagger-ui/issues/2651)*. Here's a pointer to our [multiple examples](https://github.com/HumanCellAtlas/matrix-service/blob/master/config/matrix-api.yml#L125).

We also have vignettes in progress - https://github.com/HumanCellAtlas/matrix-service/pull/309

At the moment, details about the output for each file format are documented [here](https://github.com/HumanCellAtlas/matrix-service/tree/f25a4aba9d16332104e5cc395d42db5b4426d8aa/docker-images/matrix-converter).

We would appreciate any feedback you have on V1.

I will close this issue since we have a related issue - #238 where I've referenced your request.

**Comment by pcm32** [comment]
Thanks @brianraymor we have now a working v1 client for the purposes that we need.
